package surreal.backportium.init;

import net.minecraft.block.Block;
import net.minecraft.util.ResourceLocation;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import org.jetbrains.annotations.Nullable;
import surreal.backportium.Tags;

public class ModBlocks {

    // 1.13
    public static Block BLUE_ICE;
    public static Block BUBBLE_COLUMN;
    public static Block SPRUCE_BUTTON;
    public static Block BIRCH_BUTTON;
    public static Block JUNGLE_BUTTON;
    public static Block ACACIA_BUTTON;
    public static Block DARK_OAK_BUTTON;
    public static Block SPRUCE_PRESSURE_PLATE;
    public static Block BIRCH_PRESSURE_PLATE;
    public static Block JUNGLE_PRESSURE_PLATE;
    public static Block ACACIA_PRESSURE_PLATE;
    public static Block DARK_OAK_PRESSURE_PLATE;
    public static Block SPRUCE_TRAPDOOR;
    public static Block BIRCH_TRAPDOOR;
    public static Block JUNGLE_TRAPDOOR;
    public static Block ACACIA_TRAPDOOR;
    public static Block DARK_OAK_TRAPDOOR;
    public static Block PUMPKIN;
    public static Block CONDUIT;
    public static Block TUBE_CORAL;
    public static Block DEAD_TUBE_CORAL;
    public static Block BRAIN_CORAL;
    public static Block DEAD_BRAIN_CORAL;
    public static Block BUBBLE_CORAL;
    public static Block DEAD_BUBBLE_CORAL;
    public static Block FIRE_CORAL;
    public static Block DEAD_FIRE_CORAL;
    public static Block HORN_CORAL;
    public static Block DEAD_HORN_CORAL;
    public static Block TUBE_CORAL_BLOCK;
    public static Block DEAD_TUBE_CORAL_BLOCK;
    public static Block BRAIN_CORAL_BLOCK;
    public static Block DEAD_BRAIN_CORAL_BLOCK;
    public static Block BUBBLE_CORAL_BLOCK;
    public static Block DEAD_BUBBLE_CORAL_BLOCK;
    public static Block FIRE_CORAL_BLOCK;
    public static Block DEAD_FIRE_CORAL_BLOCK;
    public static Block HORN_CORAL_BLOCK;
    public static Block DEAD_HORN_CORAL_BLOCK;
    public static Block TUBE_CORAL_FAN;
    public static Block DEAD_TUBE_CORAL_FAN;
    public static Block BRAIN_CORAL_FAN;
    public static Block DEAD_BRAIN_CORAL_FAN;
    public static Block BUBBLE_CORAL_FAN;
    public static Block DEAD_BUBBLE_CORAL_FAN;
    public static Block FIRE_CORAL_FAN;
    public static Block DEAD_FIRE_CORAL_FAN;
    public static Block HORN_CORAL_FAN;
    public static Block DEAD_HORN_CORAL_FAN;
    public static Block DRIED_KELP_BLOCK;
    public static Block KELP;
    public static Block ROUGH_PRISMARINE_STAIRS;
    public static Block PRISMARINE_BRICKS_STAIRS;
    public static Block DARK_PRISMARINE_STAIRS;
    public static Block ROUGH_PRISMARINE_SLAB;
    public static Block PRISMARINE_BRICKS_SLAB;
    public static Block DARK_PRISMARINE_SLAB;
    public static Block SEAGRASS;
    public static Block TALL_SEAGRASS;
    public static Block SEA_PICKLE;
    //public static Block SHULKER_NON_DYED;
    public static Block OAK_BARK;
    public static Block SPRUCE_BARK;
    public static Block BIRCH_BARK;
    public static Block JUNGLE_BARK;
    public static Block ACACIA_BARK;
    public static Block DARK_OAK_BARK;
    public static Block OAK_STRIPPED_LOG;
    public static Block SPRUCE_STRIPPED_LOG;
    public static Block BIRCH_STRIPPED_LOG;
    public static Block JUNGLE_STRIPPED_LOG;
    public static Block ACACIA_STRIPPED_LOG;
    public static Block DARK_OAK_STRIPPED_LOG;
    public static Block OAK_STRIPPED_BARK;
    public static Block SPRUCE_STRIPPED_BARK;
    public static Block BIRCH_STRIPPED_BARK;
    public static Block JUNGLE_STRIPPED_BARK;
    public static Block ACACIA_STRIPPED_BARK;
    public static Block DARK_OAK_STRIPPED_BARK;
    public static Block TURTLE_EGG;
    public static Block RED_MUSHROOM_BLOCK;
    public static Block BROWN_MUSHROOM_BLOCK;
    public static Block MUSHROOM_STEM;
    public static Block SMOOTH_QUARTZ;
    public static Block SMOOTH_SANDSTONE;
    public static Block SMOOTH_RED_SANDSTONE;
    public static Block SMOOTH_STONE;

    // 1.14
    public static Block BAMBOO;
    public static Block BARREL;
    public static Block BELL;
    public static Block BLAST_FURNACE;
    public static Block CAMPFIRE;
    public static Block CARTOGRAPHY_TABLE;
    public static Block COMPOSTER;
    public static Block FLETCHING_TABLE;
    public static Block GRINDSTONE;
    public static Block JIGSAW_BLOCK;
    public static Block LANTERN;
    public static Block LECTERN;
    public static Block LOOM;
    public static Block SCAFFOLDING;
    public static Block SPRUCE_SIGN;
    public static Block BIRCH_SIGN;
    public static Block JUNGLE_SIGN;
    public static Block ACACIA_SIGN;
    public static Block DARK_OAK_SIGN;
    public static Block STONE_SLAB;
    public static Block ANDESITE_SLAB;
    public static Block POLISHED_ANDESITE_SLAB;
    public static Block DIORITE_SLAB;
    public static Block POLISHED_SLAB;
    public static Block GRANITE_SLAB;
    public static Block POLISHED_GRANITE_SLAB;
    public static Block MOSSY_STONE_BRICK_SLAB;
    public static Block MOSSY_STONE_SLAB;
    public static Block MOSSY_COBBLESTONE_SLAB;
    public static Block SMOOTH_SANDSTONE_SLAB;
    public static Block CUT_SANDSTONE_SLAB;
    public static Block SMOOTH_RED_SANDSTONE_SLAB;
    public static Block CUT_RED_SANDSTONE_SLAB;
    public static Block SMOOTH_QUARTZ_SLAB;
    public static Block RED_NETHER_BRICK_SLAB;
    public static Block ENDSTONE_BRICK_SLAB;
    public static Block SMITHING_TABLE;
    public static Block SMOKER;
    public static Block POLISHED_GRANITE_STAIRS;
    public static Block MOSSY_STONE_BRICK_STAIRS;
    public static Block MOSSY_STONE_STAIRS;
    public static Block MOSSY_COBBLESTONE_STAIRS;
    public static Block SMOOTH_SANDSTONE_STAIRS;
    public static Block CUT_SANDSTONE_STAIRS;
    public static Block SMOOTH_RED_SANDSTONE_STAIRS;
    public static Block CUT_RED_SANDSTONE_STAIRS;
    public static Block SMOOTH_QUARTZ_STAIRS;
    public static Block RED_NETHER_BRICK_STAIRS;
    public static Block ENDSTONE_BRICK_STAIRS;
    public static Block STONECUTTER;
    public static Block SWEET_BERRY_BUSH;
    public static Block POLISHED_GRANITE_WALL;
    public static Block MOSSY_STONE_BRICK_WALL;
    public static Block MOSSY_STONE_WALL;
    public static Block MOSSY_COBBLESTONE_WALL;
    public static Block SMOOTH_SANDSTONE_WALL;
    public static Block CUT_SANDSTONE_WALL;
    public static Block SMOOTH_RED_SANDSTONE_WALL;
    public static Block CUT_RED_SANDSTONE_WALL;
    public static Block SMOOTH_QUARTZ_WALL;
    public static Block RED_NETHER_BRICK_WALL;
    public static Block ENDSTONE_BRICK_WALL;

    // 1.15
    public static Block BEEHIVE;
    public static Block BEE_NEST;
    public static Block HONEY_BLOCK;
    public static Block HONEYCOMB_BLOCK;

    // 1.16
    public static Block ANCIENT_DEBRIS;
    public static Block BASALT;
    public static Block BLACKSTONE;
    public static Block NETHERITE_BLOCK;
    public static Block CHAIN;
    public static Block CHISELED_NETHER_BRICKS;
    public static Block CRACKED_NETHER_BRICKS;
    public static Block CRIMSON_FUNGUS;
    public static Block WARPED_FUNGUS;
    public static Block CRIMSON_NYLIUM;
    public static Block WARPED_NYLIUM;
    public static Block CRIMSON_PLANKS;
    public static Block WARPED_PLANKS;
    public static Block CRIMSON_ROOT;
    public static Block WARPED_ROOT;
    public static Block CRIMSON_STEM;
    public static Block WARPED_STEM;
    public static Block CRIMSON_HYPHAE;
    public static Block WARPED_HYPHAE;
    public static Block CRYING_OBSIDIAN;
    public static Block GILDED_BLACKSTONE;
    public static Block LODESTONE;
    public static Block NETHER_GOLD_ORE;
    public static Block QUARTZ_BRICKS;
    public static Block RESPAWN_ANCHOR;
    public static Block SHROOMLIGHT;
    public static Block SOUL_CAMPFIRE;
    public static Block SOUL_FIRE;
    public static Block SOUL_LANTERN;
    public static Block SOUL_TORCH;
    public static Block SOUL_SOIL;
    public static Block TARGET;
    public static Block TWISTING_VINE;
    public static Block WEEPING_VINE;
    public static Block WARPED_WART_BLOCK;

    // 1.17
    public static Block AMETHYST_CLUSTER;
    public static Block AZALEA;
    public static Block AZALEA_LEAVES;
    public static Block AMETHYST_BLOCK;
    public static Block COPPER_BLOCK;
    public static Block CUT_COPPER_BLOCK;
    public static Block RAW_IRON_BLOCK;
    public static Block RAW_GOLD_BLOCK;
    public static Block RAW_COPPER_BLOCK;
    public static Block BUDDING_AMETHYST;
    public static Block CALCITE;
    public static Block CANDLE;
    public static Block CAVE_VINE;
    public static Block COBBLED_DEEPSLATE;
    public static Block COPPER_ORE;
    public static Block CUT_COPPER_SLAB;
    public static Block CUT_COPPER_STAIRS;
    public static Block DEEPSLATE;
    public static Block DEEPSLATE_SLAB;
    public static Block DEEPSLATE_STAIRS;
    public static Block DEEPSLATE_WALL;
    public static Block POLISHED_DEEPSLATE;
    public static Block POLISHED_DEEPSLATE_SLAB;
    public static Block POLISHED_DEEPSLATE_STAIRS;
    public static Block POLISHED_DEEPSLATE_WALL;
    public static Block DEEPSLATE_BRICK;
    public static Block DEEPSLATE_BRICK_SLAB;
    public static Block DEEPSLATE_BRICK_STAIRS;
    public static Block DEEPSLATE_BRICK_WALL;
    public static Block DEEPSLATE_TILE;
    public static Block DEEPSLATE_TILE_SLAB;
    public static Block DEEPSLATE_TILE_STAIRS;
    public static Block DEEPSLATE_TILE_WALL;
    public static Block DEEPSLATE_IRON_ORE;
    public static Block DEEPSLATE_GOLD_ORE;
    public static Block DEEPSLATE_COPPER_ORE;
    public static Block DEEPSLATE_COAL_ORE;
    public static Block DEEPSLATE_DIAMOND_ORE;
    public static Block DEEPSLATE_REDSTONE_ORE;
    public static Block DEEPSLATE_EMERALD_ORE;
    public static Block DEEPSLATE_LAPIS_LAZULI_ORE;
    public static Block DRIPLEAF;
    public static Block POINTED_DRIPSTONE;
    public static Block DRIPSTONE;
    public static Block GLOW_LICHEN;
    public static Block HANGING_ROOTS;
    public static Block INFESTED_DEEPSLATE;
    public static Block LIGHT_BLOCK;
    public static Block LIGHTING_ROD;
    public static Block MOSS_BLOCK;
    public static Block MOSS_CARPET;
    public static Block POTTED_AZALEA;
    public static Block POWDER_SNOW;
    public static Block ROOTED_DIRT;
    public static Block SCULK_SENSOR;
    public static Block SMOOTH_BASALT;
    public static Block SPORE_BLOSSOM;
    public static Block TINTED_GLASS;
    public static Block TUFF;

    // 1.19
    public static Block FROGLIGHT;
    public static Block FROGSPAWN;
    public static Block MANGROVE_LEAVES;
    public static Block MANGROVE_LOG;
    public static Block MANGROVE_PLANKS;
    public static Block MANGROVE_BUTTON;
    public static Block MANGROVE_DOOR;
    public static Block MANGROVE_FENCE;
    public static Block MANGROVE_FENCE_GATE;
    public static Block MANGROVE_PRESSURE_PLATE;
    public static Block MANGROVE_SIGN;
    public static Block MANGROVE_SLAB;
    public static Block MANGROVE_STAIRS;
    public static Block MANGROVE_TRAPDOOR;
    public static Block MANGROVE_PROPAGULE;
    public static Block MANGROVE_PROPAGULE_POT;
    public static Block MANGROVE_ROOTS;
    public static Block MANGROVE_WOOD;
    public static Block MUD;
    public static Block MUD_BRICKS;
    public static Block MUDDY_MANGROVE_ROOTS;
    public static Block PACKED_MUD;
    public static Block REINFORCED_DEEPSLATE;
    public static Block SCULK;
    public static Block SCULK_CATALYST;
    public static Block SCULK_SHRIEKER;
    public static Block SCULK_VEIN;

    // 1.20
    public static Block BAMBOO_MOSAIC;
    public static Block BAMBOO_PLANKS;
    public static Block BAMBOO_BLOCK;
    public static Block CALIBRATED_SCULK_SENSOR;
    public static Block CHERRY_LEAVES;
    public static Block CHERRY_PLANKS;
    public static Block CHERRY_BUTTON;
    public static Block CHERRY_DOOR;
    public static Block CHERRY_FENCE;
    public static Block CHERRY_FENCE_GATE;
    public static Block CHERRY_PRESSURE_PLATE;
    public static Block CHERRY_SIGN;
    public static Block CHERRY_SLAB;
    public static Block CHERRY_STAIRS;
    public static Block CHERRY_TRAPDOOR;
    public static Block CHERRY_SAPLING;
    public static Block CHISELED_BOOKSHELF;
    public static Block DECORATED_POT;
    public static Block HANGING_SIGN;
    public static Block SPRUCE_HANGING_SIGN;
    public static Block BIRCH_HANGING_SIGN;
    public static Block JUNGLE_HANGING_SIGN;
    public static Block ACACIA_HANGING_SIGN;
    public static Block DARK_OAK_HANGING_SIGN;
    public static Block CRIMSON_HANGING_SIGN;
    public static Block WARPED_HANGING_SIGN;
    public static Block MANGROVE_HANGING_SIGN;
    public static Block CHERRY_HANGING_SIGN;
    public static Block BAMBOO_HANGING_SIGN;
    public static Block PIGLIN_HEAD;
    public static Block PITCHER_PLANT;
    public static Block SNIFFER_EGG;
    public static Block SUSPICIOUS_GRAVEL;
    public static Block SUSPICIOUS_SAND;
    public static Block TORCHFLOWER;

    // 1.21
    public static Block CHISELED_COPPER;
    public static Block CHISELED_TUFF;
    public static Block COPPER_BULB;
    public static Block COPPER_DOOR;
    public static Block COPPER_GRATE;
    public static Block COPPER_TRAPDOOR;
    public static Block CRAFTER;
    public static Block HEAVY_CORE;
    public static Block OMINOUS_TRIAL_SPAWNER;
    public static Block OMINOUS_VAULT;
    public static Block POLISHED_TUFF;
    public static Block TRIAL_SPAWNER;
    public static Block TUFF_BRICKS;
    public static Block TUFF_SLAB;
    public static Block TUFF_STAIRS;
    public static Block TUFF_WALL;
    public static Block VAULT;

    public static void init() {
        BLUE_ICE = block("blue_ice");
        BUBBLE_COLUMN = block("bubble_column");
        SPRUCE_BUTTON = block("spruce_button");
        BIRCH_BUTTON = block("birch_button");
        JUNGLE_BUTTON = block("jungle_button");
        ACACIA_BUTTON = block("acacia_button");
        DARK_OAK_BUTTON = block("dark_oak_button");
        SPRUCE_PRESSURE_PLATE = block("spruce_pressure_plate");
        BIRCH_PRESSURE_PLATE = block("birch_pressure_plate");
        JUNGLE_PRESSURE_PLATE = block("jungle_pressure_plate");
        ACACIA_PRESSURE_PLATE = block("acacia_pressure_plate");
        DARK_OAK_PRESSURE_PLATE = block("dark_oak_pressure_plate");
        SPRUCE_TRAPDOOR = block("spruce_trapdoor");
        BIRCH_TRAPDOOR = block("birch_trapdoor");
        JUNGLE_TRAPDOOR = block("jungle_trapdoor");
        ACACIA_TRAPDOOR = block("acacia_trapdoor");
        DARK_OAK_TRAPDOOR = block("dark_oak_trapdoor");
        PUMPKIN = block("pumpkin");
        CONDUIT = block("conduit");
        TUBE_CORAL = block("tube_coral");
        DEAD_TUBE_CORAL = block("dead_tube_coral");
        BRAIN_CORAL = block("brain_coral");
        DEAD_BRAIN_CORAL = block("dead_brain_coral");
        BUBBLE_CORAL = block("bubble_coral");
        DEAD_BUBBLE_CORAL = block("dead_bubble_coral");
        FIRE_CORAL = block("fire_coral");
        DEAD_FIRE_CORAL = block("dead_fire_coral");
        HORN_CORAL = block("horn_coral");
        DEAD_HORN_CORAL = block("dead_horn_coral");
        TUBE_CORAL_BLOCK = block("tube_coral_block");
        DEAD_TUBE_CORAL_BLOCK = block("dead_tube_coral_block");
        BRAIN_CORAL_BLOCK = block("brain_coral_block");
        DEAD_BRAIN_CORAL_BLOCK = block("dead_brain_coral_block");
        BUBBLE_CORAL_BLOCK = block("bubble_coral_block");
        DEAD_BUBBLE_CORAL_BLOCK = block("dead_bubble_coral_block");
        FIRE_CORAL_BLOCK = block("fire_coral_block");
        DEAD_FIRE_CORAL_BLOCK = block("dead_fire_coral_block");
        HORN_CORAL_BLOCK = block("horn_coral_block");
        DEAD_HORN_CORAL_BLOCK = block("dead_horn_coral_block");
        TUBE_CORAL_FAN = block("tube_coral_fan");
        DEAD_TUBE_CORAL_FAN = block("dead_tube_coral_fan");
        BRAIN_CORAL_FAN = block("brain_coral_fan");
        DEAD_BRAIN_CORAL_FAN = block("dead_brain_coral_fan");
        BUBBLE_CORAL_FAN = block("bubble_coral_fan");
        DEAD_BUBBLE_CORAL_FAN = block("dead_bubble_coral_fan");
        FIRE_CORAL_FAN = block("fire_coral_fan");
        DEAD_FIRE_CORAL_FAN = block("dead_fire_coral_fan");
        HORN_CORAL_FAN = block("horn_coral_fan");
        DEAD_HORN_CORAL_FAN = block("dead_horn_coral_fan");
        DRIED_KELP_BLOCK = block("dried_kelp_block");
        KELP = block("kelp");
        ROUGH_PRISMARINE_STAIRS = block("rough_prismarine_stairs");
        PRISMARINE_BRICKS_STAIRS = block("prismarine_bricks_stairs");
        DARK_PRISMARINE_STAIRS = block("dark_prismarine_stairs");
        ROUGH_PRISMARINE_SLAB = block("rough_prismarine_slab");
        PRISMARINE_BRICKS_SLAB = block("prismarine_bricks_slab");
        DARK_PRISMARINE_SLAB = block("dark_prismarine_slab");
        SEAGRASS = block("seagrass");
        TALL_SEAGRASS = block("tall_seagrass");
        SEA_PICKLE = block("sea_pickle");
        OAK_BARK = block("oak_bark");
        SPRUCE_BARK = block("spruce_bark");
        BIRCH_BARK = block("birch_bark");
        JUNGLE_BARK = block("jungle_bark");
        ACACIA_BARK = block("acacia_bark");
        DARK_OAK_BARK = block("dark_oak_bark");
        OAK_STRIPPED_LOG = block("oak_stripped_log");
        SPRUCE_STRIPPED_LOG = block("spruce_stripped_log");
        BIRCH_STRIPPED_LOG = block("birch_stripped_log");
        JUNGLE_STRIPPED_LOG = block("jungle_stripped_log");
        ACACIA_STRIPPED_LOG = block("acacia_stripped_log");
        DARK_OAK_STRIPPED_LOG = block("dark_oak_stripped_log");
        OAK_STRIPPED_BARK = block("oak_stripped_bark");
        SPRUCE_STRIPPED_BARK = block("spruce_stripped_bark");
        BIRCH_STRIPPED_BARK = block("birch_stripped_bark");
        JUNGLE_STRIPPED_BARK = block("jungle_stripped_bark");
        ACACIA_STRIPPED_BARK = block("acacia_stripped_bark");
        DARK_OAK_STRIPPED_BARK = block("dark_oak_stripped_bark");
        TURTLE_EGG = block("turtle_egg");
        RED_MUSHROOM_BLOCK = block("red_mushroom_block");
        BROWN_MUSHROOM_BLOCK = block("brown_mushroom_block");
        MUSHROOM_STEM = block("mushroom_stem");
        SMOOTH_QUARTZ = block("smooth_quartz");
        SMOOTH_SANDSTONE = block("smooth_sandstone");
        SMOOTH_RED_SANDSTONE = block("smooth_red_sandstone");
        SMOOTH_STONE = block("smooth_stone");

        BAMBOO = block("bamboo");
        BARREL = block("barrel");
        BELL = block("bell");
        BLAST_FURNACE = block("blast_furnace");
        CAMPFIRE = block("campfire");
        CARTOGRAPHY_TABLE = block("cartography_table");
        COMPOSTER = block("composter");
        FLETCHING_TABLE = block("fletching_table");
        GRINDSTONE = block("grindstone");
        JIGSAW_BLOCK = block("jigsaw_block");
        LANTERN = block("lantern");
        LECTERN = block("lectern");
        LOOM = block("loom");
        SCAFFOLDING = block("scaffolding");
        SPRUCE_SIGN = block("spruce_sign");
        BIRCH_SIGN = block("birch_sign");
        JUNGLE_SIGN = block("jungle_sign");
        ACACIA_SIGN = block("acacia_sign");
        DARK_OAK_SIGN = block("dark_oak_sign");
        STONE_SLAB = block("stone_slab");
        ANDESITE_SLAB = block("andesite_slab");
        POLISHED_ANDESITE_SLAB = block("polished_andesite_slab");
        DIORITE_SLAB = block("diorite_slab");
        POLISHED_SLAB = block("polished_slab");
        GRANITE_SLAB = block("granite_slab");
        POLISHED_GRANITE_SLAB = block("polished_granite_slab");
        MOSSY_STONE_BRICK_SLAB = block("mossy_stone_brick_slab");
        MOSSY_STONE_SLAB = block("mossy_stone_slab");
        MOSSY_COBBLESTONE_SLAB = block("mossy_cobblestone_slab");
        SMOOTH_SANDSTONE_SLAB = block("smooth_sandstone_slab");
        CUT_SANDSTONE_SLAB = block("cut_sandstone_slab");
        SMOOTH_RED_SANDSTONE_SLAB = block("smooth_red_sandstone_slab");
        CUT_RED_SANDSTONE_SLAB = block("cut_red_sandstone_slab");
        SMOOTH_QUARTZ_SLAB = block("smooth_quartz_slab");
        RED_NETHER_BRICK_SLAB = block("red_nether_brick_slab");
        ENDSTONE_BRICK_SLAB = block("endstone_brick_slab");
        SMITHING_TABLE = block("smithing_table");
        SMOKER = block("smoker");
        POLISHED_GRANITE_STAIRS = block("polished_granite_stairs");
        MOSSY_STONE_BRICK_STAIRS = block("mossy_stone_brick_stairs");
        MOSSY_STONE_STAIRS = block("mossy_stone_stairs");
        MOSSY_COBBLESTONE_STAIRS = block("mossy_cobblestone_stairs");
        SMOOTH_SANDSTONE_STAIRS = block("smooth_sandstone_stairs");
        CUT_SANDSTONE_STAIRS = block("cut_sandstone_stairs");
        SMOOTH_RED_SANDSTONE_STAIRS = block("smooth_red_sandstone_stairs");
        CUT_RED_SANDSTONE_STAIRS = block("cut_red_sandstone_stairs");
        SMOOTH_QUARTZ_STAIRS = block("smooth_quartz_stairs");
        RED_NETHER_BRICK_STAIRS = block("red_nether_brick_stairs");
        ENDSTONE_BRICK_STAIRS = block("endstone_brick_stairs");
        STONECUTTER = block("stonecutter");
        SWEET_BERRY_BUSH = block("sweet_berry_bush");
        POLISHED_GRANITE_WALL = block("polished_granite_wall");
        MOSSY_STONE_BRICK_WALL = block("mossy_stone_brick_wall");
        MOSSY_STONE_WALL = block("mossy_stone_wall");
        MOSSY_COBBLESTONE_WALL = block("mossy_cobblestone_wall");
        SMOOTH_SANDSTONE_WALL = block("smooth_sandstone_wall");
        CUT_SANDSTONE_WALL = block("cut_sandstone_wall");
        SMOOTH_RED_SANDSTONE_WALL = block("smooth_red_sandstone_wall");
        CUT_RED_SANDSTONE_WALL = block("cut_red_sandstone_wall");
        SMOOTH_QUARTZ_WALL = block("smooth_quartz_wall");
        RED_NETHER_BRICK_WALL = block("red_nether_brick_wall");
        ENDSTONE_BRICK_WALL = block("endstone_brick_wall");

        BEEHIVE = block("beehive");
        BEE_NEST = block("bee_nest");
        HONEY_BLOCK = block("honey_block");
        HONEYCOMB_BLOCK = block("honeycomb_block");

        ANCIENT_DEBRIS = block("ancient_debris");
        BASALT = block("basalt");
        BLACKSTONE = block("blackstone");
        NETHERITE_BLOCK = block("netherite_block");
        CHAIN = block("chain");
        CHISELED_NETHER_BRICKS = block("chiseled_nether_bricks");
        CRACKED_NETHER_BRICKS = block("cracked_nether_bricks");
        CRIMSON_FUNGUS = block("crimson_fungus");
        WARPED_FUNGUS = block("warped_fungus");
        CRIMSON_NYLIUM = block("crimson_nylium");
        WARPED_NYLIUM = block("warped_nylium");
        CRIMSON_PLANKS = block("crimson_planks");
        WARPED_PLANKS = block("warped_planks");
        CRIMSON_ROOT = block("crimson_root");
        WARPED_ROOT = block("warped_root");
        CRIMSON_STEM = block("crimson_stem");
        WARPED_STEM = block("warped_stem");
        CRIMSON_HYPHAE = block("crimson_hyphae");
        WARPED_HYPHAE = block("warped_hyphae");
        CRYING_OBSIDIAN = block("crying_obsidian");
        GILDED_BLACKSTONE = block("gilded_blackstone");
        LODESTONE = block("lodestone");
        NETHER_GOLD_ORE = block("nether_gold_ore");
        QUARTZ_BRICKS = block("quartz_bricks");
        RESPAWN_ANCHOR = block("respawn_anchor");
        SHROOMLIGHT = block("shroomlight");
        SOUL_CAMPFIRE = block("soul_campfire");
        SOUL_FIRE = block("soul_fire");
        SOUL_LANTERN = block("soul_lantern");
        SOUL_TORCH = block("soul_torch");
        SOUL_SOIL = block("soul_soil");
        TARGET = block("target");
        TWISTING_VINE = block("twisted_vine");
        WEEPING_VINE = block("weeping_vine");
        WARPED_WART_BLOCK = block("warped_wart_block");

        AMETHYST_CLUSTER = block("amethyst_cluster");
        AZALEA = block("azalea");
        AZALEA_LEAVES = block("azalea_leaves");
        AMETHYST_BLOCK = block("amethyst_block");
        COPPER_BLOCK = block("copper_block");
        CUT_COPPER_BLOCK = block("cut_copper_block");
        RAW_IRON_BLOCK = block("raw_iron_block");
        RAW_GOLD_BLOCK = block("raw_gold_block");
        RAW_COPPER_BLOCK = block("raw_copper_block");
        BUDDING_AMETHYST = block("budding_amethyst");
        CALCITE = block("calcite");
        CANDLE = block("candle");
        CAVE_VINE = block("cave_vine");
        COBBLED_DEEPSLATE = block("cobbled_deepslate");
        COPPER_ORE = block("copper_ore");
        CUT_COPPER_SLAB = block("cut_copper_slab");
        CUT_COPPER_STAIRS = block("cut_copper_stairs");
        DEEPSLATE = block("deepslate");
        DEEPSLATE_SLAB = block("deepslate_slab");
        DEEPSLATE_STAIRS = block("deepslate_stairs");
        DEEPSLATE_WALL = block("deepslate_wall");
        POLISHED_DEEPSLATE = block("polished_deepslate");
        POLISHED_DEEPSLATE_SLAB = block("polished_deepslate_slab");
        POLISHED_DEEPSLATE_STAIRS = block("polished_deepslate_stairs");
        POLISHED_DEEPSLATE_WALL = block("polished_deepslate_wall");
        DEEPSLATE_BRICK = block("deepslate_brick");
        DEEPSLATE_BRICK_SLAB = block("deepslate_brick_slab");
        DEEPSLATE_BRICK_STAIRS = block("deepslate_brick_stairs");
        DEEPSLATE_BRICK_WALL = block("deepslate_brick_wall");
        DEEPSLATE_TILE = block("deepslate_tile");
        DEEPSLATE_TILE_SLAB = block("deepslate_tile_slab");
        DEEPSLATE_TILE_STAIRS = block("deepslate_tile_stairs");
        DEEPSLATE_TILE_WALL = block("deepslate_tile_wall");
        DEEPSLATE_IRON_ORE = block("deepslate_iron_ore");
        DEEPSLATE_GOLD_ORE = block("deepslate_gold_ore");
        DEEPSLATE_COPPER_ORE = block("deepslate_copper_ore");
        DEEPSLATE_COAL_ORE = block("deepslate_coal_ore");
        DEEPSLATE_DIAMOND_ORE = block("deepslate_diamond_ore");
        DEEPSLATE_REDSTONE_ORE = block("deepslate_redstone_ore");
        DEEPSLATE_EMERALD_ORE = block("deepslate_emerald_ore");
        DEEPSLATE_LAPIS_LAZULI_ORE = block("deepslate_lapis_lazuli_ore");
        DRIPLEAF = block("dripleaf");
        POINTED_DRIPSTONE = block("pointed_dripstone");
        DRIPSTONE = block("dripstone");
        GLOW_LICHEN = block("glow_lichen");
        HANGING_ROOTS = block("hanging_roots");
        INFESTED_DEEPSLATE = block("infested_deepslate");
        LIGHT_BLOCK = block("light_block");
        LIGHTING_ROD = block("lighting_rod");
        MOSS_BLOCK = block("moss_block");
        MOSS_CARPET = block("moss_carpet");
        POTTED_AZALEA = block("potted_azalea");
        POWDER_SNOW = block("powder_snow");
        ROOTED_DIRT = block("rooted_dirt");
        SCULK_SENSOR = block("sculk_sensor");
        SMOOTH_BASALT = block("smooth_basalt");
        SPORE_BLOSSOM = block("spore_blossom");
        TINTED_GLASS = block("tinted_glass");
        TUFF = block("tuff");

        FROGLIGHT = block("froglight");
        FROGSPAWN = block("frogspawn");
        MANGROVE_LEAVES = block("mangrove_leaves");
        MANGROVE_LOG = block("mangrove_log");
        MANGROVE_PLANKS = block("mangrove_planks");
        MANGROVE_BUTTON = block("mangrove_button");
        MANGROVE_DOOR = block("mangrove_door");
        MANGROVE_FENCE = block("mangrove_fence");
        MANGROVE_FENCE_GATE = block("mangrove_fence_gate");
        MANGROVE_PRESSURE_PLATE = block("mangrove_pressure_plate");
        MANGROVE_SIGN = block("mangrove_sign");
        MANGROVE_SLAB = block("mangrove_slab");
        MANGROVE_STAIRS = block("mangrove_stairs");
        MANGROVE_TRAPDOOR = block("mangrove_trapdoor");
        MANGROVE_PROPAGULE = block("mangrove_propagule");
        MANGROVE_PROPAGULE_POT = block("mangrove_propagule_pot");
        MANGROVE_ROOTS = block("mangrove_roots");
        MANGROVE_WOOD = block("mangrove_wood");
        MUD = block("mud");
        MUD_BRICKS = block("mud_bricks");
        MUDDY_MANGROVE_ROOTS = block("muddy_mangrove_roots");
        PACKED_MUD = block("packed_mud");
        REINFORCED_DEEPSLATE = block("reinforced_deepslate");
        SCULK = block("sculk");
        SCULK_CATALYST = block("sculk_catalyst");
        SCULK_SHRIEKER = block("sculk_shrieker");
        SCULK_VEIN = block("sculk_vein");

        BAMBOO_MOSAIC = block("bamboo_mosaic");
        BAMBOO_PLANKS = block("bamboo_planks");
        BAMBOO_BLOCK = block("bamboo_block");
        CALIBRATED_SCULK_SENSOR = block("calibrated_sculk_sensor");
        CHERRY_LEAVES = block("cherry_leaves");
        CHERRY_PLANKS = block("cherry_planks");
        CHERRY_BUTTON = block("cherry_button");
        CHERRY_DOOR = block("cherry_door");
        CHERRY_FENCE = block("cherry_fence");
        CHERRY_FENCE_GATE = block("cherry_fence_gate");
        CHERRY_PRESSURE_PLATE = block("cherry_pressure_plate");
        CHERRY_SIGN = block("cherry_sign");
        CHERRY_SLAB = block("cherry_slab");
        CHERRY_STAIRS = block("cherry_stairs");
        CHERRY_TRAPDOOR = block("cherry_trapdoor");
        CHERRY_SAPLING = block("cherry_sapling");
        CHISELED_BOOKSHELF = block("chiseled_bookshelf");
        DECORATED_POT = block("decorated_pot");
        HANGING_SIGN = block("hanging_sign");
        SPRUCE_HANGING_SIGN = block("spruce_hanging_sign");
        BIRCH_HANGING_SIGN = block("birch_hanging_sign");
        JUNGLE_HANGING_SIGN = block("jungle_hanging_sign");
        ACACIA_HANGING_SIGN = block("acacia_hanging_sign");
        DARK_OAK_HANGING_SIGN = block("dark_oak_hanging_sign");
        CRIMSON_HANGING_SIGN = block("crimson_hanging_sign");
        WARPED_HANGING_SIGN = block("warped_hanging_sign");
        MANGROVE_HANGING_SIGN = block("mangrove_hanging_sign");
        CHERRY_HANGING_SIGN = block("cherry_hanging_sign");
        BAMBOO_HANGING_SIGN = block("bamboo_hanging_sign");
        PIGLIN_HEAD = block("piglin_head");
        PITCHER_PLANT = block("pitcher_plant");
        SNIFFER_EGG = block("sniffer_egg");
        SUSPICIOUS_GRAVEL = block("suspicious_gravel");
        SUSPICIOUS_SAND = block("suspicious_sand");
        TORCHFLOWER = block("torchflower");

        CHISELED_COPPER = block("chiseled_copper");
        CHISELED_TUFF = block("chiseled_tuff");
        COPPER_BULB = block("copper_bulb");
        COPPER_DOOR = block("copper_door");
        COPPER_GRATE = block("copper_grate");
        COPPER_TRAPDOOR = block("copper_trapdoor");
        CRAFTER = block("crafter");
        HEAVY_CORE = block("heavy_core");
        OMINOUS_TRIAL_SPAWNER = block("ominous_trial_spawner");
        OMINOUS_VAULT = block("ominous_vault");
        POLISHED_TUFF = block("polished_tuff");
        TRIAL_SPAWNER = block("trial_spawner");
        TUFF_BRICKS = block("tuff_bricks");
        TUFF_SLAB = block("tuff_slab");
        TUFF_STAIRS = block("tuff_stairs");
        TUFF_WALL = block("tuff_wall");
        VAULT = block("vault");
    }

    @Nullable
    private static Block block(String name) {
        return ForgeRegistries.BLOCKS.getValue(new ResourceLocation(Tags.MOD_ID, name));
    }
}
