package surreal.backportium.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.fml.common.registry.ForgeRegistries;
import surreal.backportium.Tags;

// TODO Support for parrot imitation
public class ModSounds {

    // 1.13
    public static SoundEvent AMBIENT_UNDERWATER_ENTER;
    public static SoundEvent AMBIENT_UNDERWATER_EXIT;
    public static SoundEvent AMBIENT_UNDERWATER_LOOP;
    public static SoundEvent AMBIENT_UNDERWATER_LOOP_ADDITIONS;
    public static SoundEvent AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE;
    public static SoundEvent AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE;
    public static SoundEvent BLOCK_BUBBLE_COLUMN_BUBBLE_POP;
    public static SoundEvent BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT;
    public static SoundEvent BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE;
    public static SoundEvent BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT;
    public static SoundEvent BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE;
    public static SoundEvent BLOCK_CONDUIT_AMBIENT;
    public static SoundEvent BLOCK_CONDUIT_AMBIENT_SHORT;
    public static SoundEvent BLOCK_CONDUIT_ATTACK_TARGET;
    public static SoundEvent BLOCK_CONDUIT_ACTIVATE;
    public static SoundEvent BLOCK_CONDUIT_DEACTIVATE;
    public static SoundEvent BLOCK_CORAL_BLOCK_BREAK;
    public static SoundEvent BLOCK_CORAL_BLOCK_FALL;
    public static SoundEvent BLOCK_CORAL_BLOCK_HIT;
    public static SoundEvent BLOCK_CORAL_BLOCK_PLACE;
    public static SoundEvent BLOCK_CORAL_BLOCK_STEP;
    public static SoundEvent BLOCK_WET_GRASS_BREAK;
    public static SoundEvent BLOCK_WET_GRASS_FALL;
    public static SoundEvent BLOCK_WET_GRASS_HIT;
    public static SoundEvent BLOCK_WET_GRASS_PLACE;
    public static SoundEvent BLOCK_WET_GRASS_STEP;
    public static SoundEvent BLOCK_PUMPKIN_CARVE;
    public static SoundEvent ENTITY_COD_AMBIENT;
    public static SoundEvent ENTITY_COD_DEATH;
    public static SoundEvent ENTITY_COD_FLOP;
    public static SoundEvent ENTITY_COD_HURT;
    public static SoundEvent ENTITY_DOLPHIN_AMBIENT;
    public static SoundEvent ENTITY_DOLPHIN_AMBIENT_WATER;
    public static SoundEvent ENTITY_DOLPHIN_ATTACK;
    public static SoundEvent ENTITY_DOLPHIN_DEATH;
    public static SoundEvent ENTITY_DOLPHIN_EAT;
    public static SoundEvent ENTITY_DOLPHIN_HURT;
    public static SoundEvent ENTITY_DOLPHIN_JUMP;
    public static SoundEvent ENTITY_DOLPHIN_PLAY;
    public static SoundEvent ENTITY_DOLPHIN_SPLASH;
    public static SoundEvent ENTITY_DOLPHIN_SWIM;
    public static SoundEvent ENTITY_DROWNED_AMBIENT;
    public static SoundEvent ENTITY_DROWNED_DEATH;
    public static SoundEvent ENTITY_DROWNED_DEATH_WATER;
    public static SoundEvent ENTITY_DROWNED_HURT;
    public static SoundEvent ENTITY_DROWNED_HURT_WATER;
    public static SoundEvent ENTITY_DROWNED_SHOOT;
    public static SoundEvent ENTITY_DROWNED_STEP;
    public static SoundEvent ENTITY_DROWNED_SWIM;
    public static SoundEvent ENTITY_PHANTOM_AMBIENT;
    public static SoundEvent ENTITY_PHANTOM_BITE;
    public static SoundEvent ENTITY_PHANTOM_DEATH;
    public static SoundEvent ENTITY_PHANTOM_FLAP;
    public static SoundEvent ENTITY_PHANTOM_HURT;
    public static SoundEvent ENTITY_PHANTOM_SWOOP;
    public static SoundEvent ENTITY_PUFFER_FISH_AMBIENT;
    public static SoundEvent ENTITY_PUFFER_FISH_BLOW_OUT;
    public static SoundEvent ENTITY_PUFFER_FISH_BLOW_UP;
    public static SoundEvent ENTITY_PUFFER_FISH_DEATH;
    public static SoundEvent ENTITY_PUFFER_FISH_FLOP;
    public static SoundEvent ENTITY_PUFFER_FISH_HURT;
    public static SoundEvent ENTITY_PUFFER_FISH_STING;
    public static SoundEvent ENTITY_SALMON_AMBIENT;
    public static SoundEvent ENTITY_SALMON_DEATH;
    public static SoundEvent ENTITY_SALMON_FLOP;
    public static SoundEvent ENTITY_SALMON_HURT;
    public static SoundEvent ENTITY_TROPICAL_FISH_AMBIENT;
    public static SoundEvent ENTITY_TROPICAL_FISH_DEATH;
    public static SoundEvent ENTITY_TROPICAL_FISH_FLOP;
    public static SoundEvent ENTITY_TROPICAL_FISH_HURT;
    public static SoundEvent ENTITY_TURTLE_AMBIENT_LAND;
    public static SoundEvent ENTITY_TURTLE_DEATH;
    public static SoundEvent ENTITY_TURTLE_DEATH_BABY;
    public static SoundEvent ENTITY_TURTLE_EGG_BREAK;
    public static SoundEvent ENTITY_TURTLE_EGG_CRACK;
    public static SoundEvent ENTITY_TURTLE_EGG_HATCH;
    public static SoundEvent ENTITY_TURTLE_HURT;
    public static SoundEvent ENTITY_TURTLE_HURT_BABY;
    public static SoundEvent ENTITY_TURTLE_LAY_EGG;
    public static SoundEvent ENTITY_TURTLE_SHAMBLE;
    public static SoundEvent ENTITY_TURTLE_SHAMBLE_BABY;
    public static SoundEvent ENTITY_TURTLE_SWIM;
    public static SoundEvent ENTITY_SQUID_SQUIRT;
    public static SoundEvent ENTITY_HUSK_CONVERTED_TO_ZOMBIE;
    public static SoundEvent ITEM_ARMOR_EQUIP_TURTLE;
    public static SoundEvent ITEM_AXE_STRIP;
    public static SoundEvent ITEM_TRIDENT_HIT;
    public static SoundEvent ITEM_TRIDENT_HIT_GROUND;
    public static SoundEvent ITEM_TRIDENT_RETURN;
    public static SoundEvent ITEM_TRIDENT_RIPTIDE_1;
    public static SoundEvent ITEM_TRIDENT_RIPTIDE_2;
    public static SoundEvent ITEM_TRIDENT_RIPTIDE_3;
    public static SoundEvent ITEM_TRIDENT_THROW;
    public static SoundEvent ITEM_TRIDENT_THUNDER;

    public static void init() {
        AMBIENT_UNDERWATER_ENTER = soundEvent("ambient.underwater.enter");
        AMBIENT_UNDERWATER_EXIT = soundEvent("ambient.underwater.exit");
        AMBIENT_UNDERWATER_LOOP = soundEvent("ambient.underwater.loop");
        AMBIENT_UNDERWATER_LOOP_ADDITIONS = soundEvent("ambient.underwater.loop.additions");
        AMBIENT_UNDERWATER_LOOP_ADDITIONS_RARE = soundEvent("ambient.underwater.loop.additions.rare");
        AMBIENT_UNDERWATER_LOOP_ADDITIONS_ULTRA_RARE = soundEvent("ambient.underwater.loop.additions.ultra_rare");
        BLOCK_BUBBLE_COLUMN_BUBBLE_POP = soundEvent("block.bubble_column.bubble_pop");
        BLOCK_BUBBLE_COLUMN_UPWARDS_AMBIENT = soundEvent("block.bubble_column.upwards_ambient");
        BLOCK_BUBBLE_COLUMN_UPWARDS_INSIDE = soundEvent("block.bubble_column.upwards_inside");
        BLOCK_BUBBLE_COLUMN_WHIRLPOOL_AMBIENT = soundEvent("block.bubble_column.whirlpool_ambient");
        BLOCK_BUBBLE_COLUMN_WHIRLPOOL_INSIDE = soundEvent("block.bubble_column.whirlpool_inside");
        BLOCK_CONDUIT_AMBIENT = soundEvent("block.conduit.ambient");
        BLOCK_CONDUIT_AMBIENT_SHORT = soundEvent("block.conduit.ambient.short");
        BLOCK_CONDUIT_ATTACK_TARGET = soundEvent("block.conduit.attack.target");
        BLOCK_CONDUIT_ACTIVATE = soundEvent("block.conduit.activate");
        BLOCK_CONDUIT_DEACTIVATE = soundEvent("block.conduit.deactivate");
        BLOCK_CORAL_BLOCK_BREAK = soundEvent("block.coral_block.break");
        BLOCK_CORAL_BLOCK_FALL = soundEvent("block.coral_block.fall");
        BLOCK_CORAL_BLOCK_HIT = soundEvent("block.coral_block.hit");
        BLOCK_CORAL_BLOCK_PLACE = soundEvent("block.coral_block.place");
        BLOCK_CORAL_BLOCK_STEP = soundEvent("block.coral_block.step");
        BLOCK_WET_GRASS_BREAK = soundEvent("block.wet_grass.break");
        BLOCK_WET_GRASS_FALL = soundEvent("block.wet_grass.fall");
        BLOCK_WET_GRASS_HIT = soundEvent("block.wet_grass.hit");
        BLOCK_WET_GRASS_PLACE = soundEvent("block.wet_grass.place");
        BLOCK_WET_GRASS_STEP = soundEvent("block.wet_grass.step");
        BLOCK_PUMPKIN_CARVE = soundEvent("block.pumpkin.carve");
        ENTITY_COD_AMBIENT = soundEvent("entity.cod.ambient");
        ENTITY_COD_DEATH = soundEvent("entity.cod.death");
        ENTITY_COD_FLOP = soundEvent("entity.cod.flop");
        ENTITY_COD_HURT = soundEvent("entity.cod.hurt");
        ENTITY_DOLPHIN_AMBIENT = soundEvent("entity.dolphin.ambient");
        ENTITY_DOLPHIN_AMBIENT_WATER = soundEvent("entity.dolphin.ambient_water");
        ENTITY_DOLPHIN_ATTACK = soundEvent("entity.dolphin.attack");
        ENTITY_DOLPHIN_DEATH = soundEvent("entity.dolphin.death");
        ENTITY_DOLPHIN_EAT = soundEvent("entity.dolphin.eat");
        ENTITY_DOLPHIN_HURT = soundEvent("entity.dolphin.hurt");
        ENTITY_DOLPHIN_JUMP = soundEvent("entity.dolphin.jump");
        ENTITY_DOLPHIN_PLAY = soundEvent("entity.dolphin.play");
        ENTITY_DOLPHIN_SPLASH = soundEvent("entity.dolphin.splash");
        ENTITY_DOLPHIN_SWIM = soundEvent("entity.dolphin.swim");
        ENTITY_DROWNED_AMBIENT = soundEvent("entity.drowned.ambient");
        ENTITY_DROWNED_DEATH = soundEvent("entity.drowned.death");
        ENTITY_DROWNED_DEATH_WATER = soundEvent("entity.drowned.death_water");
        ENTITY_DROWNED_HURT = soundEvent("entity.drowned.hurt");
        ENTITY_DROWNED_HURT_WATER = soundEvent("entity.drowned.hurt_water");
        ENTITY_DROWNED_SHOOT = soundEvent("entity.drowned.shoot");
        ENTITY_DROWNED_STEP = soundEvent("entity.drowned.step");
        ENTITY_DROWNED_SWIM = soundEvent("entity.drowned.swim");
        ENTITY_PHANTOM_AMBIENT = soundEvent("entity.phantom.ambient");
        ENTITY_PHANTOM_BITE = soundEvent("entity.phantom.bite");
        ENTITY_PHANTOM_DEATH = soundEvent("entity.phantom.death");
        ENTITY_PHANTOM_FLAP = soundEvent("entity.phantom.flap");
        ENTITY_PHANTOM_HURT = soundEvent("entity.phantom.hurt");
        ENTITY_PHANTOM_SWOOP = soundEvent("entity.phantom.swoop");
        ENTITY_PUFFER_FISH_AMBIENT = soundEvent("entity.puffer_fish.ambient");
        ENTITY_PUFFER_FISH_BLOW_OUT = soundEvent("entity.puffer_fish.blow_out");
        ENTITY_PUFFER_FISH_BLOW_UP = soundEvent("entity.puffer_fish.blow_up");
        ENTITY_PUFFER_FISH_DEATH = soundEvent("entity.puffer_fish.death");
        ENTITY_PUFFER_FISH_FLOP = soundEvent("entity.puffer_fish.flop");
        ENTITY_PUFFER_FISH_HURT = soundEvent("entity.puffer_fish.hurt");
        ENTITY_PUFFER_FISH_STING = soundEvent("entity.puffer_fish.sting");
        ENTITY_SALMON_AMBIENT = soundEvent("entity.salmon.ambient");
        ENTITY_SALMON_DEATH = soundEvent("entity.salmon.death");
        ENTITY_SALMON_FLOP = soundEvent("entity.salmon.flop");
        ENTITY_SALMON_HURT = soundEvent("entity.salmon.hurt");
        ENTITY_TROPICAL_FISH_AMBIENT = soundEvent("entity.tropical_fish.ambient");
        ENTITY_TROPICAL_FISH_DEATH = soundEvent("entity.tropical_fish.death");
        ENTITY_TROPICAL_FISH_FLOP = soundEvent("entity.tropical_fish.flop");
        ENTITY_TROPICAL_FISH_HURT = soundEvent("entity.tropical_fish.hurt");
        ENTITY_TURTLE_AMBIENT_LAND = soundEvent("entity.turtle.ambient_land");
        ENTITY_TURTLE_DEATH = soundEvent("entity.turtle.death");
        ENTITY_TURTLE_DEATH_BABY = soundEvent("entity.turtle.death_baby");
        ENTITY_TURTLE_EGG_BREAK = soundEvent("entity.turtle.egg_break");
        ENTITY_TURTLE_EGG_CRACK = soundEvent("entity.turtle.egg_crack");
        ENTITY_TURTLE_EGG_HATCH = soundEvent("entity.turtle.egg_hatch");
        ENTITY_TURTLE_HURT = soundEvent("entity.turtle.hurt");
        ENTITY_TURTLE_HURT_BABY = soundEvent("entity.turtle.hurt_baby");
        ENTITY_TURTLE_LAY_EGG = soundEvent("entity.turtle.lay_egg");
        ENTITY_TURTLE_SHAMBLE = soundEvent("entity.turtle.shamble");
        ENTITY_TURTLE_SHAMBLE_BABY = soundEvent("entity.turtle.shamble_baby");
        ENTITY_TURTLE_SWIM = soundEvent("entity.turtle.swim");
        ENTITY_SQUID_SQUIRT = soundEvent("entity.squid.squirt");
        ENTITY_HUSK_CONVERTED_TO_ZOMBIE = soundEvent("entity.husk.converted_to_zombie");
        ITEM_ARMOR_EQUIP_TURTLE = soundEvent("item_armor_equip_turtle");
        ITEM_AXE_STRIP = soundEvent("item.axe.strip");
        ITEM_TRIDENT_HIT = soundEvent("item.trident.hit");
        ITEM_TRIDENT_HIT_GROUND = soundEvent("item.trident.hit_ground");
        ITEM_TRIDENT_RETURN = soundEvent("item.trident.return");
        ITEM_TRIDENT_RIPTIDE_1 = soundEvent("item.trident.riptide_1");
        ITEM_TRIDENT_RIPTIDE_2 = soundEvent("item.trident.riptide_2");
        ITEM_TRIDENT_RIPTIDE_3 = soundEvent("item.trident.riptide_3");
        ITEM_TRIDENT_THROW = soundEvent("item.trident.throw");
        ITEM_TRIDENT_THUNDER = soundEvent("item.trident.thunder");
    }

    private static SoundEvent soundEvent(String name) {
        return ForgeRegistries.SOUND_EVENTS.getValue(new ResourceLocation(Tags.MOD_ID, name));
    }
}
